baseURL = "https://ajbcreative.github.io/Email-Marketing/"
languageCode = 'en-us'
title = 'One Send at a Time'
theme = "hugo-coder"

# Required for blog posts to be recognized by Hugo and themes for listing, RSS etc.
mainSections = ["posts"] 

[params]
  author = "Adam Boudreau"
  info = "Email Marketing Enthusiast"
  description = "Insights and best practices for modern email marketing in our currentYear();."
  keywords = "blog, personal, email-marketing, best practices, digital marketing"

  [[params.social]]
    name = "Github"
    icon = "fa-brands fa-github fa-2x"
    weight = 1
    url = "https://github.com/AJBCreative/"

# Corrected menu configuration to include a dedicated "Home" link
[menu]
  [[menu.main]]
    name = "Home"       # This is the dedicated Home link
    weight = 1
    url = "/"           # This points to your main homepage (content/_index.md)

  [[menu.main]]
    name = "About"      # This is your dedicated About page link
    weight = 2          # Now correctly weighted after Home
    url = "/about/"     # This points to content/about/index.md

  [[menu.main]]
    name = "Blog"       # Your blog posts link
    weight = 3          # Now correctly weighted after About
    url = "/posts/"